name: IridiumEnchants
version: ${version}
description: Custom Enchants for every gamemode
main: com.iridium.iridiumenchants.IridiumEnchants
api-version: '1.13'
author: Peaches_MLG
softdepend:
  - ASkyBlock
  - Factions
  - IridiumSkyblock
  - Lands
  - TownyAdvanced
  - WorldGuard
commands:
  iridiumenchants:
    aliases: [ "enchants", "ce", "customenchants" ]
    description: Main plugin command
  gkits:
    description: Gkits command
